<a href="https://youtu.be/HhkjXxbpTbM?si=lITyK51ASIa3jPFQ">youtube link</a>

In [21]:
import numpy as np

In [22]:
size = 4
matrix = np.zeros([size,size], dtype=int)
print(matrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [23]:
for i in range(size):
    for j in range(size):
        matrix[i][j] = (i*size)+j

In [25]:
cmd = ["R", "U", "D", "L", "D", "D"]
init_row = 0
init_col = 0

In [27]:
def move(cmd, init_row, init_col, size):
    row = init_row
    col = init_col
    for c in cmd:
        if ((c=="R" ) & (col != size-1)):
            col = col + 1
        if ((c=="L") & (col != 0)):
            col = col - 1
        if((c=="U") & (row != 0)):
            row = row - 1
        if((c=="D") & (row != size-1)):
            row = row + 1
    return ((row*size)+col)

In [28]:
move(cmd, 0, 0, 4)

12